### ISSUE TITLE
No copyright & license information

### ISSUE THREAD

**Issue by czchen** [lharding/tasknc#1]
Copy from https://github.com/mjheagle8/tasknc/issues/29.

The package does not contain any copyright & license information. Lack of these means it is difficult to make it to Debian. Please help to provide these information to codebase, thanks.

**Comment by lharding** [comment]
I've added a LICENSE file (MIT) that should be compatible with any FOSS distro's legal requirements. Please let me know if there's anything else necessary to get to Debian.
