### ISSUE TITLE
tasknc can not start if there are no tasks

### ISSUE THREAD

**Issue by aignas** [lharding/tasknc#19]
I tried to run tasknc before using 'task' command and it took too long. I could start tasknc when at least one task was added via 'task add Some stuff', which is not that bad, but still, could be improved...

**Comment by mjheagle8** [comment]
I am working on a major refactor right now, will include that when it's released

**Comment by aignas** [comment]
That's great to hear!

**Comment by lharding** [comment]
With mjheagle8's blessing, I'm taking over maintenance of this project. If you still care about this issue, please reopen it over at [my fork](https://github.com/lharding/tasknc).
