### ISSUE TITLE
Could NOT find Curses (missing:  CURSES_LIBRARY)

### ISSUE THREAD

**Issue by salomonvh** [lharding/tasknc#27]
CMAKE can not find the CURSES_LIBRARY.

I had to manually do 

locate libncurses.so

Then add the following on line 150 of Findcurses.cmake

SET(CURSES_NCURSES_LIBRARY "/usr/lib/x86_64-linux-gnu/libncurses.so")

I am on Ubuntu-precise (64 bit)

**Comment by lharding** [comment]
With mjheagle8's blessing, I'm taking over maintenance of this project. If you still care about this issue, please reopen it over at [my fork](https://github.com/lharding/tasknc).

**Comment by lharding** [comment]
This should have been fixed by the recent elimination of the cmake-based build. Please feel free to reopen it if you experience it again.
