### ISSUE TITLE
tasknc is having trouble reading my task list

### ISSUE THREAD

**Issue by ghost** [lharding/tasknc#33]
I have installed tasknc and all seems to be working, but when I run the program nothing happens. Looking in /tmp/.tasknc_runlog_nigel I have a string of lines of the format "[2015-09-19 22:26:52] ERROR: error parsing task @ 1.03288}," and a final line saying: "[2015-09-19 22:26:52] ERROR: it appears that your task list is empty. tasknc does not yet support empty task lists.".

**Comment by lharding** [comment]
With mjheagle8's blessing, I'm taking over maintenance of this project. If you still care about this issue, please reopen it over at [my fork](https://github.com/lharding/tasknc).

**Comment by lharding** [comment]
I believe that this was related change in the way Taskwarrior exports tasks and was fixed by of 2c6f8d04b1485d90eb80a92707317c94a353a5ac (don't be fooled by the commit date, that pull request took several months to be merged). Please reopen this if you still experience the issue after updating.
