### ISSUE TITLE
Deleted tasks

### ISSUE THREAD

**Issue by erm3nda** [lharding/tasknc#42]
It is the common behavior to show deleted tasks?
No other tool (task, tasksh) shows them, making my experience with tasknc so much different.

**Comment by lharding** [comment]
Usually this means you need to update Taskwarrior, though I haven't looked at this behavior in a while.

It's not *supposed* to show deleted tasks.

**Comment by erm3nda** [comment]
Well, i am kinda new to taskwarrior, i must play much things before i can use it properly.

Also, tried to use ptask, which only supports up to 2.5 version. 
I tried it with 2.5.1 and didn't worked, and also didn't work with 2.5 downgraded version...
So, maybe i did mix so much things.

I've updated again to 1.5.1 and still showing old tasks i've deleted while testing.
